colors:
  body: none
  date: black
  tags: yellow
  title: none
default_hour: 9
default_minute: 0
editor: nvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default: ~/git/arca/journal.md
linewrap: 79
tagsymbols: '#@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v4.0.1

